### PR TITLE
Added promise support

### PR DESCRIPTION
**Pull request by WORMSS**
I thought I might as well add promise support to your repo.

I have done it as a subfile so it can be used completely indepentandly of non-promise method, for older/legacy versions of Node.

I could have gotten away with just using a single file for this. And that was my original plan, but I left the **"meat"** (if you can call it that) of the code in the lib folder and just used the subfile as a passthrough redirect style. If you would prefer it in a single file, then I can do that instead.

I also added a few code borders to the output part of the Readme and added a `how to` for the promise.

I attempted to add a test script, but found out you had not supplied your GruntFile and it was actually in the ignore folder. So I left it as a starting point. I've never used nodeunit so I hope I've done it right.

### CODE REVIEW

**Comment by goliatone** [comment]
@WORMSS thanks you for the PR, I will review it and let you know. 🚀

**Comment by goliatone** [comment]
@WORMSS looks good. I'm trying to figure out the best way to expose the new promise API. 

It basically boils down to this:

```
var arpscan = require('arpscan/promise');
```
VS

```
var arpscan = require('arpscan').promisify();
```

**Comment by WORMSS** [comment]
I've seen the `require("modulename/addition")` on other modules, (Can't think which off the top of my head) before in the past, and presumed it was a standard way of doing it..

When I get home I will look for which project I had seen it in.

**Comment by WORMSS** [comment]
Ahh, I remember now, it was Modernize 
https://github.com/normalize/mz

**Pull request merged**
